# Generated by Django 4.1.5 on 2023-04-03 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
