# Generated by Django 4.1.5 on 2023-04-03 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_cart_end_date_cart_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='num_days',
            field=models.IntegerField(null=True),
        ),
    ]
