# Generated by Django 4.1.5 on 2023-04-03 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_cart_num_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='price_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
