# Generated by Django 5.0.1 on 2024-03-10 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_cart_price_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_quantity',
        ),
    ]
