# Generated by Django 5.0.1 on 2024-03-10 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_remove_product_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='festival',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
